export const HATS_CONTRACT_ADDRESS =
  "0x3bc1A0Ad72417f2d411118085256fC53CBdDd137";
export const HSG_CONTRACT_ADDRESS =
  process.env.EXPO_PUBLIC_HSG_CONTRACT_ADDRESS;
export const HATS_TREE_ID = process.env.EXPO_PUBLIC_HATS_TREE_ID;
export const LEADER_HAT_ID = process.env.EXPO_PUBLIC_HATS_LEADER_ID;
export const LEADER_SAFE_ADDRESS =
  process.env.EXPO_PUBLIC_HATS_LEADER_SAFE_ACCOUNT;
export const INVITE_TTL_SECONDS = Number(
  process.env.EXPO_PUBLIC_INVITE_TTL_SECONDS || 86400
);
export const RELAYER_CONTRACT_ADDRESS =
  "0x85c93B4d068dbaB44D86006dfd6d52179534EB79";
export const CHAIN_ID = process.env.EXPO_PUBLIC_CHAIN_ID;
export const PROJECT_ID = process.env.EXPO_PUBLIC_WC_PROJECT_ID;
export const RELAYID_API_URL = process.env.EXPO_PUBLIC_RELAYID_API_URL;
export const RELAYID_APP_API_TOKEN =
  process.env.EXPO_PUBLIC_RELAYID_APP_API_TOKEN;
export const STELLAR_API_URL =
  process.env.EXPO_PUBLIC_STELLAR_API_URL || "http://localhost:3000";
